static-build/qemu: Common apply patches script
kata-containers/packaging pull request #1162
Opened 2020-10-16 20:04 UTC by wainersm

Creates a common script to the qemu and qemu-virtiofs build
processes to ensure the patches are applied of same way.

Backport of github.com/kata-containers/kata-containers/pull/787,
with the three commits squashed.

Fixes: #786

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

2020-10-19 10:08 UTC, jodh-intel requested changes

2020-10-19 10:08 UTC, jodh-intel commented on qemu/apply_patches.sh
> +	for patch in $(find $patches_dir -name '*.patch'); do
Given the number of bugs we've had in the past with applying patches, I'd suggest moving this to the top-level `scripts/` directory and allow `$patches_dir` to be a CLI param to this script.

But note that this script isn't reliable as it isn't sorting the patches numerically (as you do manually below).

2020-10-19 10:08 UTC, jodh-intel commented on static-build/qemu-virtiofs/Dockerfile
> +	done;fi
Please change this block to:

- Add the `sort` functionality to `apply_patches.sh`.
- Call `apply_patches.sh $VIRTIOFS_PATCHES_DIR`.

2020-10-20 17:49 UTC, wainersm commented
Hi @jodh-intel ! Since this is a back-port of already merged github.com/kata-containers/kata-containers/pull/787 , I think I should implement your suggestions on the original tree first so that the code do not diverge and future back-ports can be made easily. Any objection?

2020-10-21 08:57 UTC, jodh-intel commented
@wainersm - agreed! I've raised https://github.com/kata-containers/kata-containers/issues/1014 to handle the improvements.

2020-10-21 08:57 UTC, jodh-intel approved these changes

2020-10-23 15:06 UTC, wainersm commented
/test-ubuntu-18-04

2020-10-23 15:06 UTC, wainersm commented
/test-ubuntu

2020-10-23 16:04 UTC, wainersm commented
@jodh-intel @fidencio am I allowed to trigger the obs-packaging-ci job? If yes, how?

2020-10-29 18:32 UTC, wainersm commented
/AzurePipelines run

2020-10-29 18:53 UTC, wainersm commented
@jodh-intel I decided to include the backport of https://github.com/kata-containers/kata-containers/pull/1025 in this same PR, so we have the change in a single place.

2020-10-29 18:53 UTC, wainersm commented
/test ubuntu

2020-10-29 19:10 UTC, jcvenegas commented
/AzurePipelines run

2020-10-29 20:10 UTC, wainersm commented
The jenkins-ci-ubuntu-18-04 failed because of a checking in the kernel files:

```
16:37:38 Check Changes in kernel
16:37:38 kernel/build-kernel.sh
16:37:38 scripts/apply_patches.sh
16:37:38 static-build/qemu-virtiofs/Dockerfile
16:37:38 static-build/qemu/Dockerfile
16:37:38 Kernel directory has changes check kernel/kata_config_version changed
16:37:38 ERROR: Please bump version in kernel/kata_config_version
```
Should any updated file (including build scripts and README)  in the kernel directory drive to `kata_config_version` increment?

2020-10-30 08:08 UTC, jodh-intel commented
> Should any updated file (including build scripts and README) in the kernel directory drive to `kata_config_version` increment?

@wainersm - yes: https://github.com/kata-containers/packaging/blob/master/.ci/test.sh#L39..L56 :)

2020-10-30 18:56 UTC, wainersm commented
/test ubuntu

2020-10-31 00:22 UTC, amshinde commented
/AzurePipelines run

2020-11-03 21:36 UTC, jcvenegas approved these changes

2020-11-03 21:36 UTC, merged

2020-11-03 21:37 UTC, jcvenegas commented
@wainersm could you backport to stable-1.11 and stable-1.12 as well ?

2020-11-10 17:51 UTC, wainersm commented
> @wainersm could you backport to stable-1.11 and stable-1.12 as well ?

yes @jcvenegas , I will backport to those branches as well.