add BPF related kernel config
kata-containers/packaging pull request #1171
Opened 2020-11-09 20:16 UTC by pwang7

add BPF related kernel config flags, so that people can run BPF with customized kernel in Kata

2020-11-09 21:45 UTC, devimc commented
thanks @pwang7 - Could you please elaborate on your commit message? why we need this and what are you fixing?
take a look to this https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

I  wonder what could be the performance impact of this change

/test-qemu-metrics
/test-metrics

2020-11-09 21:46 UTC, devimc commented
/test-ubuntu-qemu-metrics

2020-11-10 05:41 UTC, pwang7 commented
> what

@devimc  Thanks for your reply!

This PR is to enable BPF related features in kernel, when building a customized kernel for Kata.

Without these BPF related features enabled in kernel, many BPF programs cannot run in Kata, such as using BPF for tracing, network filtering, etc.

The main purpose of this PR is to facilitate BPF developers to run their BPF code in Kata. Since BPF is of active development in kernel community, and many BPF related new features require very recent kernel 5.8+. With this PR to enable BPF features in kernel, it's easy to run and test BPF programs in Kata with multiple customized new kernel versions. Otherwise BPF developers have to install multiple kernel versions to their dev machines and switch to different kernels by reboot.

2020-11-10 16:46 UTC, devimc commented
Thanks @pwang7 

> The main purpose of this PR is to facilitate BPF developers to run their BPF code in Kata. Since BPF is of active development in kernel community, and many BPF related new features require very recent kernel 5.8+. With this PR to enable BPF features in kernel, it's easy to run and test BPF programs in Kata with multiple customized new kernel versions. Otherwise BPF developers have to install multiple kernel versions to their dev machines and switch to different kernels by reboot.

That makes sense, but since not all users/developers may need BPF, it should be optional.
would you mind reworking your pull request to make BPF optional? It would be great if you can add an option (--bpf) to `build-kernel.sh` to enable it.
Take a look to this PR https://github.com/kata-containers/packaging/pull/938/files -  it can help you as reference.

Thanks

2020-11-11 04:17 UTC, pwang7 commented
> Thanks @pwang7
> 
> > The main purpose of this PR is to facilitate BPF developers to run their BPF code in Kata. Since BPF is of active development in kernel community, and many BPF related new features require very recent kernel 5.8+. With this PR to enable BPF features in kernel, it's easy to run and test BPF programs in Kata with multiple customized new kernel versions. Otherwise BPF developers have to install multiple kernel versions to their dev machines and switch to different kernels by reboot.
> 
> That makes sense, but since not all users/developers may need BPF, it should be optional.
> would you mind reworking your pull request to make BPF optional? It would be great if you can add an option (--bpf) to `build-kernel.sh` to enable it.
> Take a look to this PR https://github.com/kata-containers/packaging/pull/938/files - it can help you as reference.
> 
> Thanks

Just updated according to your suggestion, please review.

2020-11-11 09:35 UTC, jodh-intel approved these changes
Thanks @pwang7.

2020-11-11 09:35 UTC, jodh-intel commented on kernel/README.md
> +	-b          : Enable BPF related features in kernel.
Nit: This hasn't been added to the list of options alphabetically - it should come first.

2020-11-11 09:35 UTC, jodh-intel commented on kernel/build-kernel.sh
> +	-b          : Enable BPF related features in kernel.
Same comment as above. Not necessary for this PR, but I'd personally remove the hard-coded output of the script in the README and tell users they can run `build-kernel.sh -h` for further info in the doc - easier maintenance! :smile:

2020-11-11 09:35 UTC, jodh-intel commented on kernel/build-kernel.sh
> +	if [[ ${enable_bpf_kernel_configs} == "true" ]]; then
Nit: You don't need to use double square brackets here.

2020-11-11 09:35 UTC, jodh-intel commented on kernel/build-kernel.sh
> +	fi
Nit: Missing blank line after `fi`.

2020-11-11 09:35 UTC, jodh-intel commented on kernel/configs/fragments/common/bpf.conf
> +# for tc filters
How about adding a 1 line comment explaining what the file is for (using the term Berkeley Packet Filter than just bpf)?

2020-11-11 12:09 UTC, pwang7 commented
> Thanks @pwang7.

Just updated according to your review comments.

2020-11-11 15:37 UTC, devimc commented
/test

2020-11-11 15:37 UTC, devimc commented
/AzurePipelines run

2020-11-11 15:49 UTC, devimc requested changes
thanks @pwang7 - could you please update your commit message?, it needs a `fixes #NNNN` and a body, see https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

2020-11-11 20:19 UTC, pwang7 commented
> thanks @pwang7 - could you please update your commit message?, it needs a `fixes #NNNN` and a body, see https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

Do I need to file an issue first? Since I don't have issue number now.

2020-11-11 20:34 UTC, devimc commented
> Do I need to file an issue first? Since I don't have issue number now.

yes, please

2020-11-12 12:17 UTC, pwang7 commented
> > Do I need to file an issue first? Since I don't have issue number now.
> 
> yes, please

Updated.

2020-11-12 13:17 UTC, devimc commented
/test

2020-11-12 13:17 UTC, devimc commented
/AzurePipelines run

2020-11-12 15:05 UTC, devimc approved these changes
thanks @pwang7

2020-11-12 15:05 UTC, merged